language: python
python:
  - "2.7"
  #- "3.2" # Not supported
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
install:
  - pip install -r requirements.txt
  - pip install -U -r test-requirements.txt
script: pytest --cov=./
after_success: ./scripts/after_success.sh
